
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow to suggest a competitive price for a vehicle based on its details and current market trends in India.
 *
 * - suggestListingPrice - A function that suggests a listing price for a vehicle.
 * - SuggestListingPriceInput - The input type for the suggestListingPrice function.
 * - SuggestListingPriceOutput - The return type for the suggestListingPrice function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestListingPriceInputSchema = z.object({
  make: z.string().describe('The make of the vehicle.'),
  model: z.string().describe('The model of the vehicle.'),
  year: z.number().describe('The year of the vehicle.'),
  mileage: z.number().describe('The mileage of the vehicle in kilometers.'),
  condition: z
    .string()
    .describe(
      'The condition of the vehicle (e.g., Excellent, Good, Fair, Poor).'
    ),
  zipCode: z.string().describe('The Pincode (6-digit) where the vehicle is located in India.'), // Changed from zipCode to Pincode
});
export type SuggestListingPriceInput = z.infer<typeof SuggestListingPriceInputSchema>;

const SuggestListingPriceOutputSchema = z.object({
  suggestedPrice: z.number().describe('The suggested listing price for the vehicle in INR (Indian Rupees).'),
  marketAnalysis: z
    .string()
    .describe(
      'An analysis of the current market trends in India and how they affect the suggested price.'
    ),
});
export type SuggestListingPriceOutput = z.infer<typeof SuggestListingPriceOutputSchema>;

export async function suggestListingPrice(
  input: SuggestListingPriceInput
): Promise<SuggestListingPriceOutput> {
  return suggestListingPriceFlow(input);
}

const suggestListingPricePrompt = ai.definePrompt({
  name: 'suggestListingPricePrompt',
  input: {schema: SuggestListingPriceInputSchema},
  output: {schema: SuggestListingPriceOutputSchema},
  prompt: `You are an expert in vehicle pricing for the Indian market. Given the details of a vehicle and its location (Pincode), you will suggest a competitive price for the vehicle in INR and provide a brief market analysis relevant to India.

Vehicle Details:
Make: {{{make}}}
Model: {{{model}}}
Year: {{{year}}}
Mileage: {{{mileage}}} km
Condition: {{{condition}}}
Pincode: {{{zipCode}}}

Based on these details, what is a competitive listing price in Indian Rupees (INR) and why? Provide a brief market analysis to support your suggestion, considering Indian market conditions.
`,
});

const suggestListingPriceFlow = ai.defineFlow(
  {
    name: 'suggestListingPriceFlow',
    inputSchema: SuggestListingPriceInputSchema,
    outputSchema: SuggestListingPriceOutputSchema,
  },
  async input => {
    const {output} = await suggestListingPricePrompt(input);
    // Ensure suggestedPrice is a number
    if (output && typeof output.suggestedPrice === 'string') {
        output.suggestedPrice = parseFloat(output.suggestedPrice.replace(/[^0-9.-]+/g,"")) || 0;
    } else if (output && typeof output.suggestedPrice !== 'number') {
        output.suggestedPrice = 0;
    }
    return output!;
  }
);
